version: '2'

services:
  # An example hello world web service
  web:
    image: crccheck/hello-world
    environment:
      VIRTUAL_HOST: example.com
      VIRTUAL_PORT: 80 
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: admin@example.com
      # For testing purposes
      LETSENCRYPT_TEST: "true"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/path/to/etc/nginx/vhost.d:/etc/nginx/vhost.d"
      - "/path/to/usr/share/nginx/html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/path/to/etc/nginx/certs:/etc/nginx/certs"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    environment:
      # only necessary, when in testmode
      ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory
